title: "Simon Hampton"
description: "Functional Fullstack Freelancer working in Elm, Elixir, Javascript and Haskell"

url: "https://simonh1000.github.io"

permalink: /:year/:month/:title/

github: [Repository metadata]

safe: true
lsi: false

defaults:
  layout: "default"

sass:
  sass_dir: _sass
